introduce interpolation functionality to project
websdk/rhumb pull request #22
Opened 2017-03-31 14:01 UTC by matthewdunsdon

This enables Rhumb to interpolate params to produce paths.

This does not do anything with encoding or decoding the values of
params, so params with "/" and "?" characters in the values will produce
paths that the user may not expect.  This is out of scope for this PR,
though it will definitely be fixed later.

## Motivation and Context

See [GH-18](https://github.com/websdk/rhumb/pull/18).

## How Was This Tested?

Unit tests have been created.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change follows the style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the [contribution guidelines](../CONTRIBUTING.md)
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2017-03-31 16:14 UTC, mstade approved these changes
Looking real good chief. 👍

2017-03-31 16:14 UTC, mstade commented on README.md
> +When variables are present, Rhumb is will interpolate the variables with the params you supply:
Typo: `Rhumb is will`, should be `Rhumb will`

2017-03-31 16:14 UTC, mstade commented on README.md
> +When you give `.interpolate(...)` a route without any declared variables or partial variable parts, then you will not see much changes:
Maybe this should say that `.interpolate(...)` *will* escape the result if necessary, and show an example?

2017-03-31 16:14 UTC, mstade commented on README.md
> +For interpolation to produce a valid path, it will throw and error when a required variable is absent, `""`, `null` or `undefined`:
Typo: `throw and error` should be `throw an error`

2017-03-31 16:14 UTC, mstade commented on README.md
> +It will also throw and error when a required partial variable is absent, `""`, `null` or `undefined`:
Typo: `throw and error` should be `throw an error`

2017-03-31 16:14 UTC, mstade commented on README.md
> +Rhumb has is greedy with how it handles optional paths when interpolating, so expect optional parts to be included whenever possible.
Typo: `Rhumb has is` should be `Rhumb is`

2017-03-31 16:14 UTC, mstade commented on README.md
> +When variables or partially variables in optional parts are absent, `""`, `null` or `undefined` then no error is thown and the optional part is dropped.
Typo: `thown` should be `thrown`

2017-03-31 16:15 UTC, mstade requested changes
Sorry, didn't mean to approve prematurely. Just get those typos fixed and maybe add that escape example in there and it's ready to go I think.

2017-04-03 09:17 UTC, matthewdunsdon commented
Added description about escaping, so would appreciate a review of those changes.

2017-04-03 10:18 UTC, mstade approved these changes
Looks great!

2017-04-03 11:15 UTC, mstade commented
I'll merge and release these changes today @matthewdunsdon, unless you see any reason to hold off?

2017-04-03 12:08 UTC, matthewdunsdon commented
I was initially thinking that we hold off releasing till encoding or decoding the values of params has been done.

I am fine if we release what we have got, so that I can get to work on updating some of the packages that depend on this like [websdk/nap](https://github.com/websdk/nap).

2017-04-03 13:16 UTC, mstade commented
No you're right @matthewdunsdon, let's do it when the whole shebang is done. Should we merge this PR though?

2017-04-04 08:47 UTC, merged